apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: kh4d43hvo-dotnet-basic-gitops-repository
spec:
  url: https://github.com/testrhtaporg/kh4d43hvo-dotnet-basic-gitops